import CustomMantineProvider from "@/providers/CustomMantineProvider";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <CustomMantineProvider>{children}</CustomMantineProvider>
      </body>
    </html>
  );
}
